# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7_8oNukEHKfEYWK_eTfenP3z8gRliDT
"""

import pickle
import os
arr = [["Systems analyst", "Tester"],
       ["Database administrator",
        "Data Analytics",
        "Data Engineering",
        "Data scientist",
        "Business Analyst"],

       ["Data scientist",
        "Machine Learning Engineer"],

       ["Blockchain Developer",
        "Blockchain Solution Architect",
        "Blockchain Legal Consultant"],
       ["Full-stack developer",
        "Frontend Developer",
        "Backend Dveloper",
        "Android developer",
        "Software developer"],
       ["Cloud engineer",
        "Cloud Development",
        "Cybersecurity"],
       ["Game developer"],
       ["Hardware engineer"],
       ["HR"]]
quer = ["How good are you in memorizing?",
        "Rate yourself at socializing.",
        "Your will of taking the risk of pursuing a unexplored career.",
        "Rate yourself for your destructive(toys) nature in your childhood.",
        "How will you rate yourself for interest in coding or programming ?",
        "Your level of interest in statistics and probability.",
        "If 0 represent short length movies and 10 represent long length movies , rate your choice of  movie.",
        "How was your third language(sanskrit or any new language) in school ?",
        "Rate you designing(can say drawing) skills.",
        "What will be the level of your interest in creating the product over selling the product?",
        "How interested are you in learning till you work in industry?",
        "If 0 represent simplicity and 10 represent chaos , rate yourself in this category of life you want.",
        "Your level of interest in sales and marketing.",
        "How was your maths in your 11th and 12th?"]


def make_it(answers):
    # answers = []
    # for i in range(14):
    #     print(quer[i])
    #     ans = int(input())
    #     answers.append(ans)
    row = [answers]
    cwd = os.getcwd()
    infile = open(cwd + r'/GapUpFrontend/users/gapup_model.pkl', 'rb')
    model = pickle.load(infile)
    yhat = model.predict(row)
    results = []
    for i in arr:
        if yhat in i:
            # print(i)
            results.append(i)
            break
    result = [entry for entry in results[0]]
    infile.close()
    return result



def main():
    make_it()


if __name__ == "__main__":
    main()
